name = "comptia-certifications-study"
compatibility_date = "2024-10-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "certifications-db"
database_id = "f902b6eb-3cfa-46be-b7f9-2b287eb35e2c"
