export const CERTS = [
  // ── CORE ─────────────────────────────────────────────────────────────────
  {
    id: 'itf-plus',
    name: 'ITF+',
    fullName: 'CompTIA IT Fundamentals',
    code: 'FC0-U61',
    badge: 'ITF',
    color: 'slate',
    passingScore: 650,
    questionCount: 75,
    duration: '60 minutes',
    description: 'Entry-level IT concepts: hardware, software, networking, security, and databases.',
    pathway: 'core',
    status: 'active',
    resources: [
      { label: 'Official exam page', href: 'https://www.comptia.org/en-us/certifications/it-fundamentals/', kind: 'docs' },
    ],
  },
  {
    id: 'a-plus',
    name: 'A+',
    fullName: 'CompTIA A+',
    code: '220-1201 / 220-1202',
    badge: 'A+',
    color: 'emerald',
    passingScore: 700,
    questionCount: 90,
    duration: '90 min per exam',
    description: 'Hardware, OS, networking, security, and troubleshooting for IT support roles.',
    note: 'Requires two exams: Core 1 (220-1201) and Core 2 (220-1202)',
    pathway: 'core',
    status: 'active',
    resources: [
      { label: 'Messer — Core 1 (220-1201)', href: 'https://www.professormesser.com/get-a-plus-core-1-certified/', kind: 'video' },
      { label: 'Messer — Core 2 (220-1202)', href: 'https://www.professormesser.com/get-a-plus-core-2-certified/', kind: 'video' },
      { label: 'Messer on YouTube', href: 'https://www.youtube.com/professormesser', kind: 'video' },
      { label: 'Official exam page', href: 'https://www.comptia.org/en-us/certifications/a/', kind: 'docs' },
    ],
  },
  {
    id: 'network-plus',
    name: 'Network+',
    fullName: 'CompTIA Network+',
    code: 'N10-009',
    badge: 'N+',
    color: 'blue',
    passingScore: 720,
    questionCount: 90,
    duration: '90 minutes',
    description: 'Networking fundamentals, protocols, infrastructure, and troubleshooting.',
    pathway: 'core',
    status: 'active',
    resources: [
      { label: 'Messer — N10-009 course', href: 'https://www.professormesser.com/get-n10-009-network-plus-certified/', kind: 'video' },
      { label: 'Messer on YouTube', href: 'https://www.youtube.com/professormesser', kind: 'video' },
      { label: 'Official exam page', href: 'https://www.comptia.org/en-us/certifications/network/', kind: 'docs' },
    ],
  },
  {
    id: 'security-plus',
    name: 'Security+',
    fullName: 'CompTIA Security+',
    code: 'SY0-701',
    badge: 'Sec+',
    color: 'rose',
    passingScore: 750,
    questionCount: 90,
    duration: '90 minutes',
    description: 'Core cybersecurity skills: threats, architecture, operations, and compliance.',
    pathway: 'core',
    status: 'active',
    resources: [
      { label: 'Messer — SY0-701 course', href: 'https://www.professormesser.com/sy0-701-certification-course/', kind: 'video' },
      { label: 'Messer on YouTube', href: 'https://www.youtube.com/professormesser', kind: 'video' },
      { label: 'Official exam page', href: 'https://www.comptia.org/en-us/certifications/security/', kind: 'docs' },
    ],
  },
  // ── INFRASTRUCTURE ────────────────────────────────────────────────────────
  {
    id: 'server-plus',
    name: 'Server+',
    fullName: 'CompTIA Server+',
    code: 'SK0-005',
    badge: 'S+',
    color: 'orange',
    passingScore: 750,
    questionCount: 90,
    duration: '90 minutes',
    description: 'Server hardware, administration, virtualization, security, and disaster recovery.',
    pathway: 'infrastructure',
    status: 'active',
    // Professor Messer has no Server+ course — his catalog covers only A+, Network+ and Security+.
    resources: [
      { label: 'Official exam page', href: 'https://www.comptia.org/en-us/certifications/server/', kind: 'docs' },
    ],
  },
  {
    id: 'linux-plus',
    name: 'Linux+',
    fullName: 'CompTIA Linux+',
    code: 'XK0-005',
    badge: 'LX+',
    color: 'yellow',
    passingScore: 720,
    questionCount: 90,
    duration: '90 minutes',
    description: 'Linux system administration, security, and scripting for modern infrastructure.',
    pathway: 'infrastructure',
    status: 'active',
    resources: [
      { label: 'Official exam page', href: 'https://www.comptia.org/en-us/certifications/linux/', kind: 'docs' },
    ],
  },
  {
    id: 'cloud-plus',
    name: 'Cloud+',
    fullName: 'CompTIA Cloud+',
    code: 'CV0-004',
    badge: 'CL+',
    color: 'sky',
    passingScore: 750,
    questionCount: 90,
    duration: '90 minutes',
    description: 'Cloud infrastructure, security, deployment models, and hybrid environments.',
    pathway: 'infrastructure',
    status: 'active',
    resources: [
      { label: 'Official exam page', href: 'https://www.comptia.org/en-us/certifications/cloud/', kind: 'docs' },
    ],
  },
  // ── CYBERSECURITY ─────────────────────────────────────────────────────────
  {
    id: 'cysa-plus',
    name: 'CySA+',
    fullName: 'CompTIA CySA+',
    code: 'CS0-003',
    badge: 'CySA',
    color: 'purple',
    passingScore: 750,
    questionCount: 85,
    duration: '165 minutes',
    description: 'Cybersecurity analyst skills: threat detection, analysis, and incident response.',
    pathway: 'cybersecurity',
    status: 'active',
    resources: [
      { label: 'Official exam page', href: 'https://www.comptia.org/en-us/certifications/cybersecurity-analyst/', kind: 'docs' },
    ],
  },
  {
    id: 'pentest-plus',
    name: 'PenTest+',
    fullName: 'CompTIA PenTest+',
    code: 'PT0-003',
    badge: 'PT+',
    color: 'red',
    passingScore: 750,
    questionCount: 85,
    duration: '165 minutes',
    description: 'Penetration testing, vulnerability assessment, and ethical hacking techniques.',
    pathway: 'cybersecurity',
    status: 'active',
    resources: [
      { label: 'Official exam page', href: 'https://www.comptia.org/en-us/certifications/pentest/', kind: 'docs' },
    ],
  },
  {
    id: 'casp-plus',
    name: 'CASP+',
    fullName: 'CompTIA CASP+',
    code: 'CAS-004',
    badge: 'CASP',
    color: 'crimson',
    passingScore: null,
    questionCount: 90,
    duration: '165 minutes',
    description: 'Advanced security architecture, risk management, and enterprise security integration.',
    pathway: 'cybersecurity',
    status: 'active',
    resources: [
      { label: 'Official exam page', href: 'https://www.comptia.org/en-us/certifications/securityx/', kind: 'docs' },
    ],
    note: 'Pass/fail only — no numeric score reported',
  },
  // ── DATA ──────────────────────────────────────────────────────────────────
  {
    id: 'datasys-plus',
    name: 'DataSys+',
    fullName: 'CompTIA DataSys+',
    code: 'DS0-001',
    badge: 'DS+',
    color: 'teal',
    passingScore: 750,
    questionCount: 90,
    duration: '90 minutes',
    description: 'Database administration, data management, and analytics fundamentals.',
    pathway: 'data',
    status: 'active',
    resources: [
      { label: 'Official exam page', href: 'https://www.comptia.org/en-us/certifications/datasys/', kind: 'docs' },
    ],
  },
  // ── VOICE & UC ────────────────────────────────────────────────────────────
  // Not a CompTIA exam — vendor platform training for real deployments.
  {
    id: 'threecx',
    name: '3CX On-Prem',
    fullName: '3CX Phone System — Self-Hosted (v20)',
    code: 'Self-hosted / BYO hardware',
    badge: '3CX',
    color: 'violet',
    passingScore: null,
    questionCount: 48,
    duration: 'Self-paced',
    description: 'Deploying and running 3CX v20 on your own Debian 12 hardware: install, trunks, call flow, security, and maintenance.',
    pathway: 'voice',
    status: 'active',
    note: 'Vendor training, not a CompTIA exam — quiz scores here are practice only. Always confirm commands and licensing against the current 3CX docs before a live deployment.',
    resources: [
      { label: '3CX Manual — installing on Debian', href: 'https://www.3cx.com/docs/manual/installing-debian-linux-pbx/', kind: 'docs' },
      { label: '3CX Manual — firewall & router config', href: 'https://www.3cx.com/docs/manual/firewall-router-configuration/', kind: 'docs' },
      { label: '3CX Manual — SIP trunks', href: 'https://www.3cx.com/docs/manual/sip-trunks/', kind: 'docs' },
      { label: '3CX Manual — full documentation', href: 'https://www.3cx.com/docs/manual/', kind: 'docs' },
      { label: '3CX Academy — free certification training', href: 'https://www.3cx.com/3cxacademy/', kind: 'docs' },
      { label: '3CX Academy — Basic track', href: 'https://www.3cx.com/3cxacademy/basic/', kind: 'docs' },
      { label: '3CX Academy — Advanced track', href: 'https://www.3cx.com/3cxacademy/advanced/', kind: 'docs' },
      { label: '3CX pricing & editions (verify current tiers here)', href: 'https://www.3cx.com/ordering/pricing/', kind: 'docs' },
      { label: '3CX community forums', href: 'https://www.3cx.com/community/', kind: 'docs' },
      // Video — 3CX official channel plus the Voxtelesys "Quick Start Guide" V20 series,
      // which is the most practical walkthrough set available for v20 admin tasks.
      { label: '3CX official YouTube channel', href: 'https://www.youtube.com/@3cx-Global', kind: 'video' },
      { label: 'Quick Start Guide playlist (V20 series)', href: 'https://www.youtube.com/playlist?list=PLSi2UwGgWaasLpyTCUM3WJqZbEons9Iaf', kind: 'video' },
      { label: 'V20 Add Users walkthrough', href: 'https://www.youtube.com/watch?v=g6PYF3Y6lys', kind: 'video' },
      { label: 'V20 SIP Trunk Setup', href: 'https://www.youtube.com/watch?v=uroy8U8Zd3w', kind: 'video' },
      { label: 'V20 Add 911 / emergency rule', href: 'https://www.youtube.com/watch?v=tIY2ZGPVPQA', kind: 'video' },
      { label: 'V20 SBC Setup (remote sites)', href: 'https://www.youtube.com/watch?v=bBLoaEmhWXM', kind: 'video' },
      { label: 'V20 Add Departments', href: 'https://www.youtube.com/watch?v=Xw0Eov_rp1M', kind: 'video' },
      { label: 'V20 Admin Portal tour', href: 'https://www.youtube.com/watch?v=sfD1ujmOCls', kind: 'video' },
      { label: '3CX Web Client demo', href: 'https://www.youtube.com/watch?v=PThgwEumRwU', kind: 'video' },
      { label: 'Debian server setup for 3CX (older version, still useful)', href: 'https://www.youtube.com/watch?v=ZN2Pk1dph08', kind: 'video' },
      { label: 'V18 to V20 upgrade walkthrough', href: 'https://www.youtube.com/watch?v=na9yopTquzY', kind: 'video' },
      { label: 'V20 upgrade checklist & FAQ webinar (3CX)', href: 'https://www.youtube.com/watch?v=ORCpsEqlRks', kind: 'video' },
      { label: 'Installing the V20 Windows softphone', href: 'https://www.youtube.com/watch?v=q3oOyRgob50', kind: 'video' },
    ],
  },
]

export const PATHWAYS = [
  { id: 'core',           label: 'Core',           description: 'Foundation certifications for all IT roles' },
  { id: 'infrastructure', label: 'Infrastructure',  description: 'Servers, Linux, and cloud systems' },
  { id: 'cybersecurity',  label: 'Cybersecurity',   description: 'Security analysis, testing, and architecture' },
  { id: 'data',           label: 'Data',            description: 'Databases and data systems' },
  { id: 'voice',          label: 'Voice & UC',      description: 'Phone systems and unified communications platforms' },
]

export const CERT_COLORS = {
  blue:    { bg: 'bg-blue-600',    dim: 'bg-blue-600/10',    border: 'border-blue-600/40',    text: 'text-blue-400',    bar: 'bg-blue-500',    badge: 'bg-blue-600/20 text-blue-300',    hover: 'hover:bg-blue-600/15'    },
  emerald: { bg: 'bg-emerald-600', dim: 'bg-emerald-600/10', border: 'border-emerald-600/40', text: 'text-emerald-400', bar: 'bg-emerald-500', badge: 'bg-emerald-600/20 text-emerald-300', hover: 'hover:bg-emerald-600/15' },
  orange:  { bg: 'bg-orange-600',  dim: 'bg-orange-600/10',  border: 'border-orange-600/40',  text: 'text-orange-400',  bar: 'bg-orange-500',  badge: 'bg-orange-600/20 text-orange-300',  hover: 'hover:bg-orange-600/15'  },
  rose:    { bg: 'bg-rose-600',    dim: 'bg-rose-600/10',    border: 'border-rose-600/40',    text: 'text-rose-400',    bar: 'bg-rose-500',    badge: 'bg-rose-600/20 text-rose-300',    hover: 'hover:bg-rose-600/15'    },
  violet:  { bg: 'bg-violet-600',  dim: 'bg-violet-600/10',  border: 'border-violet-600/40',  text: 'text-violet-400',  bar: 'bg-violet-500',  badge: 'bg-violet-600/20 text-violet-300',  hover: 'hover:bg-violet-600/15'  },
  amber:   { bg: 'bg-amber-600',   dim: 'bg-amber-600/10',   border: 'border-amber-600/40',   text: 'text-amber-400',   bar: 'bg-amber-500',   badge: 'bg-amber-600/20 text-amber-300',   hover: 'hover:bg-amber-600/15'   },
  red:     { bg: 'bg-red-600',     dim: 'bg-red-600/10',     border: 'border-red-600/40',     text: 'text-red-400',     bar: 'bg-red-500',     badge: 'bg-red-600/20 text-red-300',     hover: 'hover:bg-red-600/15'     },
  yellow:  { bg: 'bg-yellow-500',  dim: 'bg-yellow-500/10',  border: 'border-yellow-500/40',  text: 'text-yellow-400',  bar: 'bg-yellow-400',  badge: 'bg-yellow-500/20 text-yellow-300',  hover: 'hover:bg-yellow-500/15'  },
  sky:     { bg: 'bg-sky-600',     dim: 'bg-sky-600/10',     border: 'border-sky-600/40',     text: 'text-sky-400',     bar: 'bg-sky-500',     badge: 'bg-sky-600/20 text-sky-300',     hover: 'hover:bg-sky-600/15'     },
  purple:  { bg: 'bg-purple-600',  dim: 'bg-purple-600/10',  border: 'border-purple-600/40',  text: 'text-purple-400',  bar: 'bg-purple-500',  badge: 'bg-purple-600/20 text-purple-300',  hover: 'hover:bg-purple-600/15'  },
  teal:    { bg: 'bg-teal-600',    dim: 'bg-teal-600/10',    border: 'border-teal-600/40',    text: 'text-teal-400',    bar: 'bg-teal-500',    badge: 'bg-teal-600/20 text-teal-300',    hover: 'hover:bg-teal-600/15'    },
  slate:   { bg: 'bg-slate-600',   dim: 'bg-slate-600/10',   border: 'border-slate-600/40',   text: 'text-slate-400',   bar: 'bg-slate-500',   badge: 'bg-slate-600/20 text-slate-300',   hover: 'hover:bg-slate-600/15'   },
  crimson: { bg: 'bg-red-800',     dim: 'bg-red-900/20',     border: 'border-red-800/40',     text: 'text-red-300',     bar: 'bg-red-700',     badge: 'bg-red-900/30 text-red-300',     hover: 'hover:bg-red-900/20'     },
}

export function getCert(id) { return CERTS.find((c) => c.id === id) }
export function getActiveCerts() { return CERTS.filter((c) => c.status === 'active') }
